### ISSUE TITLE
Iris fails to write screenshot on firstrun on MacOS

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1188]
After doing a fresh install of Iris and working around issues #1186 and #1187, I get an error message when initiating Iris that indicates a failure to write a screenshot file.

Here is my terminal output:
```
(iris) Anthonys-MacBook-Pro:iris ashughes$ iris
screencapture: cannot write file to intended destination, .screenshot2018-0925_14-54-38-946397.png
Traceback (most recent call last):
  File "/Users/ashughes/iris/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/ashughes/iris/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ashughes/iris/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/Users/ashughes/iris/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/ashughes/iris/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ashughes/iris/iris/__main__.py", line 18, in <module>
    import firefox.app as fa
  File "/Users/ashughes/iris/iris/firefox/app.py", line 5, in <module>
    from iris.api.core.platform import Platform
  File "/Users/ashughes/iris/iris/api/core/platform.py", line 9, in <module>
    class Platform(object):
  File "/Users/ashughes/iris/iris/api/core/platform.py", line 20, in Platform
    HIGH_DEF = not (pyautogui.screenshot().size == pyautogui.size())
  File "/Users/ashughes/iris/lib/python2.7/site-packages/pyscreeze/__init__.py", line 331, in _screenshot_osx
    im = Image.open(tmpFilename)
  File "/Users/ashughes/iris/lib/python2.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '.screenshot2018-0925_14-54-38-946397.png'
```

**Comment by mwobensmith** [comment]
Similar to #933, the solution will be the same.

**Comment by mwobensmith** [comment]
@ashughes1 A quick workaround: If you are on Mac Retina, change line 20 in platform.py to this:

`
    HIGH_DEF = True
`
If you are on a non-Retina Mac, make it `False`.

See if that works.

**Comment by mwobensmith** [comment]
Note to self: related to #632

**Comment by ashughes1** [comment]
Hi @mwobensmith your proposed workaround did not work. I still get the same error. Note that I've hit this now on three different Macs:

- 2018 13" Retina Macbook Pro running MacOS Mojave
- 2013 13" Retina Macbook Pro running MacOS High Sierra
- 2009 Mac Mini running MacOS El Capitan with 1080p LCD display connected via miniDP

**Comment by mwobensmith** [comment]
When the `pyautogui.screenshot()` argument has a filename, the error appears to go away.

i.e.
`pyautogui.screenshot('.temp.png')`

This will write the file `.temp.png` to the root Iris module directory. We can a) name this file whatever we want, b) remove it when Iris quits and/or c) add it to the `.gitignore` file so that it is never tracked or checked into the repo.

**Comment by mwobensmith** [comment]
Above solution won't work. Getting an intermittent error that it can't find the temp file. Chasing this via another solution in #1302.

**Comment by thepurpleana** [comment]
Hi @mwobensmith! I'm here from Outreachy and I'm facing this problem. 
I tried changing permissions on the folder and changing the HIGH_DEF value, but it's not working. 

I will try to get iris running on windows in the mean time!

**Comment by mwobensmith** [comment]
Hi @thepurpleana , one thing you can do is try the branch `dev` and see if the problem goes away. We are currently fixing this issue, and the `dev` branch has a partial fix that might work for you.
