### ISSUE TITLE
Pipenv install returns 'pyobjc' errors on Windows and Linux

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1282]
There are now a bunch of errors that pipenv throws when installing all dependencies.
And for me `Iris` does not run any more on Windows 10.
I think this is a Pipenv issue.
This needs to be investigated.

```Installing dependencies from Pipfile.lock (1d9910)…
An error occurred while installing pyobjc-framework-webkit==5.0
An error occurred while installing pyobjc-framework-screensaver==5.0
An error occurred while installing pyobjc-framework-discrecording==5.0
An error occurred while installing pyobjc-framework-cfnetwork==5.0
An error occurred while installing pyobjc-framework-addressbook==5.0
An error occurred while installing pyobjc-framework-security==5.0
```

![image](https://user-images.githubusercontent.com/2787766/46726512-306e8200-cc87-11e8-90e1-68827a98b351.png)

**Comment by AndreiH** [comment]
`Pipenv shell` currently fails for me on the latest pipenv version

``` pipenv shell
Launching subshell in virtual environment…
Traceback (most recent call last):
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Andrei Hutusoru\scoop\apps\python27\current\scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\cli\command.py", line 374, in shell
    pypi_mirror=state.pypi_mirror,
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\core.py", line 2058, in do_shell
    shell.fork(*fork_args)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\shells.py", line 95, in fork
    with self.inject_path(venv):
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\shells.py", line 147, in inject_path
    with NamedTemporaryFile("w+") as rcfile:
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 283, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 131, in _sanitize_params
    output_type = _infer_return_type(prefix, suffix, dir)
  File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 30, in _infer_return_type
    return _types.pop()
KeyError: 'pop from an empty set```

**Comment by AndreiH** [comment]
`Pipfile.lock` was also accidentally deleted from the repo. This needs to be readded.

**Comment by AndreiH** [comment]
> `Pipenv shell` currently fails for me on the latest pipenv version
> 
> ```
> Launching subshell in virtual environment…
> Traceback (most recent call last):
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Users\Andrei Hutusoru\scoop\apps\python27\current\scripts\pipenv.exe\__main__.py", line 9, in <module>
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\cli\command.py", line 374, in shell
>     pypi_mirror=state.pypi_mirror,
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\core.py", line 2058, in do_shell
>     shell.fork(*fork_args)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\shells.py", line 95, in fork
>     with self.inject_path(venv):
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\contextlib.py", line 17, in __enter__
>     return self.gen.next()
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\shells.py", line 147, in inject_path
>     with NamedTemporaryFile("w+") as rcfile:
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 283, in NamedTemporaryFile
>     prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 131, in _sanitize_params
>     output_type = _infer_return_type(prefix, suffix, dir)
>   File "c:\users\andrei hutusoru\scoop\apps\python27\current\lib\site-packages\pipenv\_compat.py", line 30, in _infer_return_type
>     return _types.pop()
> KeyError: 'pop from an empty set'```
> ```

Found the issue regarding this one. It seems that running the `iris` command from `Git Bash` terminal will end-up giving that error, but when running from CMD or Powershell, all is ok and runs perfectly.

**Comment by AndreiH** [comment]
`Pipfile.lock` was also accidentally deleted from the repo. Cannot find the commit,
 This needs to be readded.

**Comment by AndreiH** [comment]
This is ready for review on branch "issue_1282". Also added the Upgrade option of Pipenv to all Bootstrap scripts

**Comment by silviuFlorin** [comment]
Code approved
