### ISSUE TITLE
iris fails to run on Windows 10

### ISSUE THREAD

**Issue by wizofe** [mozilla/iris#1307]
Following the steps on the Wiki (successfully until the launch of `iris`):

```
C:\Users\wizofe\_dev\outreachy18\iris\iris (master -> origin)
(iris-sGkjK-hm) λ iris
Traceback (most recent call last):
  File "C:\Users\wizofe\.virtualenvs\iris-sGkjK-hm\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "c:\users\wizofe\_dev\outreachy18\iris\iris\__main__.py", line 46, in main
    Iris()
  File "c:\users\wizofe\_dev\outreachy18\iris\iris\__main__.py", line 57, in __init__
    if self.control_center():
  File "c:\users\wizofe\_dev\outreachy18\iris\iris\__main__.py", line 110, in control_center
    launch_firefox(fx_path, profile=profile_path, url=self.base_local_web_url)
  File "c:\users\wizofe\_dev\outreachy18\iris\iris\api\helpers\general.py", line 48, in launch_firefox
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\wizofe\scoop\apps\python27\current\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Users\wizofe\scoop\apps\python27\current\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Unfortunately I can't load it :(

**Comment by mwobensmith** [comment]
Hi @wizofe can you try to run again like this?

`iris -k -i DEBUG`

Let me know what it says.

**Comment by mwobensmith** [comment]
Also, do you have Firefox installed?

**Comment by wizofe** [comment]
Firefox Developer Edition 🤦‍♂️ 

Indeed the debug shows it's of course Firefox. Thank you!

````bash
2018-10-16 02:37:59 [DEBUG] [iris.api.helpers.general] Launching Firefox with arguments: C:\Program Files\Mozilla Firefox\firefox -foreground -no-remote -profile C:\Users\wizofe\.iris\cc_profile -new-tab http://127.0.0.1:2000

Traceback (most recent call last):
  File "C:\Users\wizofe\.virtualenvs\iris-sGkjK-hm\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "c:\users\wizofe\_dev\outreachy18\iris\iris\__main__.py", line 46, in main
    Iris()
```

**Comment by mwobensmith** [comment]
It should detect your local install of Firefox and open the Control Center. I realize that we left the part about installing Firefox out of the setup instructions. We'll fix that. But is it working for you now?

**Comment by wizofe** [comment]
Yes now it starts but still, it doesn't want to run most of the test cases. Mostly because it can't find the image `iris.png`. Also concerning tesseract on windows, there was an issue with a broken link but I contacted the people there and they fixed it; so now you should be updated as well.

https://github.com/tesseract-ocr/tesseract/issues/689

It's an inconsistency though as on the Wiki instructions you ask to install version 4, while on the bootstrap it gets version 3.5. Is that intentional?

**Comment by mwobensmith** [comment]
Regarding the error, what is your screen resolution? 

Regarding Tesseract, our instructions were wrong. We will handle all of this in the bootstrap. We're fixing that now, so let us know when it's done if it works better. :)

**Comment by wizofe** [comment]
My resolution is 2880x1880. I'm using a MacBook Pro (when it was really Pro) I think 2014 15". :)

**Comment by silviuFlorin** [comment]
@wizofe Do you have 2 or more displays?

**Comment by wizofe** [comment]
No just one @silviuFlorin

**Comment by AndreiH** [comment]
@wizofe are you still experimenting this ? This seems to be an issue with Firefox not being found to be launched. 
Please see that you have Firefox latest stable release installed in one of the default paths on Windows:
`C:\\Program Files\\Mozilla Firefox\\firefox.exe`
or
`C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe`

**Comment by wizofe** [comment]
To be honest I am not, as I switched to my dev Linux machine and it works fine. I can go back and double check though. I am using not having installed Firefox but Firefox Dev Edition and that installs in a different location I expect.

Can you add different flavours of Firefox so that people with different versions can still use the Dashboard?

**Comment by wizofe** [comment]
I can verify that is fixed.
