### ISSUE TITLE
Cannot launch firefox on testing Debian

### ISSUE THREAD

**Issue by wizofe** [mozilla/iris#1317]
After the bootstrap, `pipenv install` and `pipenv shell` when I execute `iris` I get:

```
(iris) wizofe@kvasir:~/_dev/outreachy18/mozilla/iris$ iris
Traceback (most recent call last):
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/__main__.py", line 46, in main
    Iris()
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/__main__.py", line 57, in __init__
    if self.control_center():
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/__main__.py", line 110, in control_center
    launch_firefox(fx_path, profile=profile_path, url=self.base_local_web_url)
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/api/helpers/general.py", line 48, in launch_firefox
    subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Now, that is probably the reason that I am not having firefox on the correct path. If I run `iris -i -k DEBUG` though, `iris` is downloading the firefox version that needs for testing and starts executing tests.

As per discussion before, I expect that the first firefox instance that `iris` think is missing (mind you, I have the Firefox Developer Edition so it's in a custom path) results in the second case running the full tests (and I don't get the Iris Control Center).

**Comment by mwobensmith** [comment]
Hi @wizofe, have you tried the `dev` branch? I believe I fixed this yesterday in #1308. This assumes that your Firefox install is in one of the paths specified in `__main__.py`, lines 103-116.

```
if Settings.get_os() == Platform.MAC:
    paths.append('/Applications/Firefox.app/Contents/MacOS/firefox')
    paths.append('/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox')
    paths.append('/Applications/Firefox Nightly.app/Contents/MacOS/firefox')
elif Settings.get_os() == Platform.WINDOWS:
    paths.append('C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe')
    paths.append('C:\\Program Files (x86)\\Firefox Developer Edition\\firefox.exe')
    paths.append('C:\\Program Files (x86)\\Nightly\\firefox.exe')
    paths.append('C:\\Program Files\\Mozilla Firefox\\firefox.exe')
    paths.append('C:\\Program Files\\Firefox Developer Edition\\firefox.exe')
    paths.append('C:\\Program Files\\Nightly\\firefox.exe')
else:
    paths.append('/usr/bin/firefox')
    paths.append('/usr/lib/firefox/firefox')
```

The code above is looking for your local Firefox install to launch the control center. As you mentioned, the build that Iris uses to run tests is a different build.

**Comment by wizofe** [comment]
From the `dev` branch I get this:

```
(iris) wizofe@kvasir:~/_dev/outreachy18/mozilla/iris$ iris
Traceback (most recent call last):
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/wizofe/.local/share/virtualenvs/iris-gJS0tnSG/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/__main__.py", line 25, in <module>
    from api.helpers.general import launch_firefox, quit_firefox, get_firefox_channel, get_firefox_version, \
  File "/home/wizofe/_dev/outreachy18/mozilla/iris/iris/api/helpers/general.py", line 8, in <module>
    from mozprofile import FirefoxProfile
ImportError: No module named mozprofile
```

**Comment by mwobensmith** [comment]
Did you by any chance run `pipenv install`?  There is a new dependency in that branch that you are missing.

**Comment by mwobensmith** [comment]
Hmmmm, I am not sure. If it were me, I'd first use `exit` to leave the active`pipenv`, and then the normal steps of `pipenv install`, `pipenv shell` and then `iris`. If that does not work, give me a bit. I'm about to land some code that could change this.

**Comment by mwobensmith** [comment]
The `dev` branch has been updated, try it.

**Comment by wizofe** [comment]
Cool, I am on it :)

**Comment by wizofe** [comment]
```
(iris) wizofe@kvasir:~/_dev/outreachy18/mozilla/iris$ iris
2018-10-17 16:34:58 [ERROR] [iris.__main__] Can't find local Firefox installation, aborting Iris run.
```

Is that the intention? If yes, success :) :tada:

**Comment by mwobensmith** [comment]
@wizofe Uh, maybe? It just means that your Firefox install is not in the expected path. Can you put a symlink there, or just install Firefox in one of those locations?

**Comment by wizofe** [comment]
I can confirm that create a symlink in `/usr/bin` and via the `devel` branch solves that issue. That confirms also iris working on the latest Debian Buster (still in testing).

**Comment by wizofe** [comment]
I can verify that's fixed.
