### ISSUE TITLE
`private_window_menu_zoom_controls` test fails on Mac, needs investigation

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1522]
This test is failing on Mac intermittently and needs to be investigated.
It maybe caused by the upgrade to Tesseract 4, maybe captured area is too small.
On other platforms it passes. 

See stack trace below:

```
2018-11-22 17:20:36 [INFO] [iris.test_runner] Executing: 1 - [private_window_menu_zoom_controls]: This is a test case that checks the zoom indicator in a private window when applying the Firefox Menu Zoom Controls.
2018-11-22 17:20:54 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Page successfully loaded, firefox logo found.
2018-11-22 17:20:57 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: Zoom indicator not displayed by default in the url bar.
2018-11-22 17:21:04 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: By default zoom indicator is 100% in hamburger menu.
screencapture: cannot write file to intended destination, .screenshot2018-1122_17-21-11-683048.png
Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/mozilla_iris-YG1EtssF/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/mozilla_iris/iris/__main__.py", line 38, in main
    run_iris()
  File "/Users/iris/mozilla_iris/iris/__main__.py", line 108, in run_iris
    run(master_test_list, tests, browser)
  File "/Users/iris/mozilla_iris/iris/test_runner.py", line 69, in run
    current.run()
  File "/Users/iris/mozilla_iris/iris/tests/zoom_indicator/private_window_menu_zoom_controls.py", line 48, in run
    expected = new_region.exists('110%', 10)
  File "/Users/iris/mozilla_iris/iris/api/core/region.py", line 141, in exists
    return exists(what, timeout, self)
  File "/Users/iris/mozilla_iris/iris/api/core/region.py", line 546, in exists
    wait(pattern, timeout, in_region)
  File "/Users/iris/mozilla_iris/iris/api/core/region.py", line 523, in wait
    a_match = text_search_by(image_name, True, region)
  File "/Users/iris/mozilla_iris/iris/api/core/util/ocr_search.py", line 218, in text_search_by
    match_object['width'] + 6, match_object['height'] + 4))
  File "/Users/iris/.local/share/virtualenvs/mozilla_iris-YG1EtssF/lib/python2.7/site-packages/pyscreeze/__init__.py", line 331, in _screenshot_osx
    im = Image.open(tmpFilename)
  File "/Users/iris/.local/share/virtualenvs/mozilla_iris-YG1EtssF/lib/python2.7/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '.screenshot2018-1122_17-21-11-683048.png'
```

**Comment by icrisan** [comment]
In fact there are 4 test cases that FAIL with the same reason:
private_window_menu_zoom_controls.py
private_window_keyboard_keys.py
reset_zoom_level_hamburger_menu.py
zoom_in_hamburger_menu.py

**Comment by AndreiH** [comment]
Found the cause of these failures on MAC.
These are failing because OCR search wants to zoom in on the region screenshot, if the text is not found in the first instance.
https://github.com/mozilla/iris/blob/master/iris/api/core/util/ocr_search.py#L217
We no longer use PyAutoGui  here, so the screenshot is not found to zoom on.
I will do the necessary changes in OCR search

**Comment by AndreiH** [comment]
@mwobensmith I opened a PR for this https://github.com/mozilla/iris/pull/1597
Can you review it ? Thanks !

**Comment by icrisan** [comment]
@mwobensmith  I merged Andrei's branch because Silviu is not at work today and he needs those changes to continue his work with tesseract. We tested this branch and all looks good.

**Comment by AndreiH** [comment]
Thanks @icrisan !
