### ISSUE TITLE
Create batch script to run many update tests at once

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1642]
Release QA would like the ability to trigger many iris runs at once, with different parameters. This would be ideally suited for update tests across locales, e.g.:

```
iris -l ro -f 65.0b10 -e beta-cdntest -t manual_update -o
iris -l fr -f 65.0b10 -e beta -t background_update -o
iris -l ja -f 65.0b10 -e beta-cdntest -t manual_update -o
```

**Comment by AndreiH** [comment]
@ashughes1 Do we want the `locales` and `channel` hard-coded in the bash script?
I know Bogdan has a list of `locales`.
Or do we want  the `locales` and `channel` specified every time from the command line when executing the bash script?

**Comment by tracywalker** [comment]
They will edit the batch script for the various combinations of build, locale and channel to be tested.  The idea is that they run the batch script once which itself kicks off each of the required Iris test runs to complete the update verification pass for that test cycle.

**Comment by AndreiH** [comment]
I finished creating the script, and it can be found here: https://github.com/mozilla/iris/pull/2000

Discussing more with Bogdan Maris, I created the script to best follow his needs.
After some brainstorming we reached to this final script.

The script is currently run like this:
`./iris/tests/update/assets/update_tests.sh --locales=fr,ro,ar,en-US,vi --versions=65.0b10,64.0b3,63.0b5,59.0b6`
And it tests the firs locale with the first version, the second locale with the second version (background and manual firefox update)
You can specify up to 20 versions and 20 locales, but we can increase that number.
Let me know what you think. Cheers!

**Comment by tracywalker** [comment]
The two tests to be added to the -t are:
default_search_code_google and default_search_code_yandex

**Comment by AndreiH** [comment]
Updated !

**Comment by ashughes1** [comment]
@AndreiH I'm not able to get the script to work. No matter what I enter it always gives me "The Firefox version and locale has not been specified". 

I've tried running:
`./tools/run_update_suite.sh -l fr,ro,ar,en-US,vi -v 64.0b10,64.0b3,63.0b5,62.0b2 -c beta`
and
`./tools/run_update_suite.sh --locales=fr,ro,ar,en-US,vi --versions=64.0b10,64.0b3,63.0b5,62.0b2 --channel=beta`

Can you provide me some documentation for this script?

**Comment by AndreiH** [comment]
@ashughes1 this is because the script was not updated correctly after issue https://github.com/mozilla/iris/issues/1641 was fixed and merged.

I prepared a PR that fixes this here: https://github.com/mozilla/iris/pull/2497

After this is merged into dev, the correct commands will be with `=`:  
```./tools/run_update_suite.sh --locales=fr,ro,ar,en-US,vi --versions=64.0b10,64.0b3,63.0b5,62.0b2 --channel=beta```
or
```./tools/run_update_suite.sh --locales=fr,ro,ar,en-US,vi --versions=64.0b10,64.0b3,63.0b5,62.0b2 --channel=beta```

**Comment by ashughes1** [comment]
Thanks @AndreiH. I see this was merged to dev so I tested it again on the dev branch. I'm getting an error on MacOS though. Please let me know if you need a separate issue filed for this.

```
(iris) bash-3.2$ ./tools/run_update_suite.sh --locales=fr,de,en-US --versions=64.0b10,64.0b5,63.0b6,62.0b2 --channel=beta


Starting MANUAL update test: 

LOCALE = fr
FIREFOX VERSION = 64.0b10
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator


Starting BACKGROUND update test: 

LOCALE = fr
FIREFOX VERSION = 64.0b10
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator


Starting MANUAL update test: 

LOCALE = de
FIREFOX VERSION = 64.0b5
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator


Starting BACKGROUND update test: 

LOCALE = de
FIREFOX VERSION = 64.0b5
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator


Starting MANUAL update test: 

LOCALE = en-US
FIREFOX VERSION = 63.0b6
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator


Starting BACKGROUND update test: 

LOCALE = en-US
FIREFOX VERSION = 63.0b6
CHANNEL = beta


Traceback (most recent call last):
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/iris/Development/iris/iris/__main__.py", line 13, in <module>
    from api.core.key import check_keyboard_state
  File "/Users/iris/Development/iris/iris/api/core/key.py", line 10, in <module>
    import pyautogui
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/Users/iris/.local/share/virtualenvs/iris-FrnbsRKg/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator
```

**Comment by AndreiH** [comment]
@ashughes1 This is because of issue https://github.com/mozilla/iris/issues/2477
You have to do a `pipenv install` again, for the dependencies of the project to update.

**Comment by ashughes1** [comment]
Thanks @AndreiH, it works now.
