### ISSUE TITLE
Fix position_window_restored test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1908]
`position_window_restored` is failing inside of our cron job run. Please notice that the test passes when is run as a single test.

Please consider the error log attached bellow:

```

Traceback (most recent call last):                                                                         «
»   File "C:\Users\svuser\.virtualenvs\iris-NcrgrEXF\Scripts\iris-script.py", line 11, in <module>           «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                  «
»   File "c:\iriscron2\iris\iris\__main__.py", line 38, in main                                              «
»     run_iris()                                                                                             «
»   File "c:\iriscron2\iris\iris\__main__.py", line 108, in run_iris                                         «
»     run(master_test_list, tests, browser)                                                                  «
»   File "c:\iriscron2\iris\iris\test_runner.py", line 69, in run                                            «
»     current.run()                                                                                          «
»   File "c:\iriscron2\iris\iris\tests\session_restore\position_window_restored.py", line 149, in run        «
»     assert_true(self, focus_site_restored and firefox_test_site_restored, 'Session restored successfully') «
»   File "c:\iriscron2\iris\iris\asserts.py", line 61, in assert_true                                        «
»     assert_equal(test_case, actual, True, message)                                                         «
»   File "c:\iriscron2\iris\iris\asserts.py", line 32, in assert_equal                                       «
»     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) 

```

**Comment by pavelciapa** [comment]
@tracywalker, sure, I have some ideas about this

**Comment by yeyartsev** [comment]
Cannot reproduce
