### ISSUE TITLE
Fix scroll_each_window test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1909]
`scroll_each_window` is failing during our cron job run with the following error:

```

» Traceback (most recent call last):                                                                     «
»   File "C:\Users\svuser\.virtualenvs\iris-NcrgrEXF\Scripts\iris-script.py", line 11, in <module>       «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                              «
»   File "c:\iriscron2\iris\iris\__main__.py", line 38, in main                                          «
»     run_iris()                                                                                         «
»   File "c:\iriscron2\iris\iris\__main__.py", line 108, in run_iris                                     «
»     run(master_test_list, tests, browser)                                                              «
»   File "c:\iriscron2\iris\iris\test_runner.py", line 69, in run                                        «
»     current.run()                                                                                      «
»   File "c:\iriscron2\iris\iris\tests\session_restore\scroll_each_window.py", line 128, in run          «
»     assert_true(self, hamburger_menu_quit_displayed, 'Hamburger menu quit item displayed.')            «
»   File "c:\iriscron2\iris\iris\asserts.py", line 61, in assert_true                                    «
»     assert_equal(test_case, actual, True, message)                                                     «
»   File "c:\iriscron2\iris\iris\asserts.py", line 32, in assert_equal                                   «
»     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) 

```

Please notice that this error was encountered until now only on `osx` and `Win 10` platforms

**Comment by tracywalker** [comment]
Hey guys, please investigate and fix this failing test case.

**Comment by spronoza** [comment]
Ok, will be done

**Comment by spronoza** [comment]
Cannot reproduce at dev branch
@dmitrybakaev please take a look
