### ISSUE TITLE
Fix nasa_tv_heavy_content test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1912]
`nasa_tv_heavy_content` test case is failing during our cron job run with the following error:

```

» Traceback (most recent call last):                                                                     «
»   File "C:\Users\andrei.filip\.virtualenvs\iris-FZG5OCmB\Scripts\iris-script.py", line 11, in <module> «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                              «
»   File "c:\prototype\iris\iris\__main__.py", line 38, in main                                          «
»     run_iris()                                                                                         «
»   File "c:\prototype\iris\iris\__main__.py", line 108, in run_iris                                     «
»     run(master_test_list, tests, browser)                                                              «
»   File "c:\prototype\iris\iris\test_runner.py", line 69, in run                                        «
»     current.run()                                                                                      «
»   File "c:\prototype\iris\iris\tests\plugin_compatibility\nasa_tv_heavy_content.py", line 33, in run   «
»     assert_true(self, video_playing, 'The video is playing and the speaker icon is displayed')         «
»   File "c:\prototype\iris\iris\asserts.py", line 61, in assert_true                                    «
»     assert_equal(test_case, actual, True, message)                                                     «
»   File "c:\prototype\iris\iris\asserts.py", line 32, in assert_equal                                   «
»     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) 

```

Please notice that this issue was encountered until now on osx and Win7 platforms.

**Comment by tracywalker** [comment]
Pavel, please investigate and fix this failing test.

**Comment by pavelciapa** [comment]
@tracywalker, ok, I will

**Comment by paulprokhorovmoz** [comment]
We cannot reproduce this issue, please send screenshots of your run.
