### ISSUE TITLE
Fix no_search_form_history test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1913]
`no_search_form_history` is failing during our cron job run with the following error:

```
» Traceback (most recent call last):                                                       «
»   File "c:\prototype\iris\iris\test_runner.py", line 69, in run                          «
»     current.run()                                                                        «
»   File "c:\prototype\iris\iris\tests\privacy\no_search_form_history.py", line 19, in run «
»     remember_history_pattern = Pattern('remember_history.png')                           «
»   File "c:\prototype\iris\iris\api\core\pattern.py", line 37, in __init__                «
»     path = _get_image_path(inspect.stack()[1][1], image_name)                            «
»   File "c:\prototype\iris\iris\api\core\pattern.py", line 301, in _get_image_path        «
»     raise FindError('Pattern not found.')                                                «
» FindError: Pattern not found.                             

```
Please notice that this test is failing on all the platforms due to a missing pattern.

**Comment by dbakaev** [comment]
@tracywalker investigating, will get back on this asap.

**Comment by dbakaev** [comment]
@tracywalker I am unable to track the root cause of the absence for this file. Currently, branch #1767 contains this file and the file was there at the moment of code review (tests case was passing for all the OS). The only guess that somehow it was excluded during merge into dev. I'll add a new branch with the fix.

**Comment by dbakaev** [comment]
Added missing images https://github.com/mozilla/iris/pull/1916, please merge.
