### ISSUE TITLE
Manual update test hangs and fails on Windows 10 (65.0 Beta)

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1930]
Here is the sample output from my machine:
```
(iris-R3GGJVZj) C:\Users\iris\iris>iris -f 65.0b11 -d update -o
2019-01-25 14:33:49 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/65.0b11-candidates/
2019-01-25 14:33:50 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-01-25 14:33:50 [INFO] [mozdownload.scraper] Selected build: build1
2019-01-25 14:33:50 [INFO] [mozdownload.scraper] Downloading from: https://archive.mozilla.org/pub/firefox/candidates/65.0b11-candidates/build1/win64/en-US/Firefox%20Setup%2065.0b11.exe
2019-01-25 14:33:50 [INFO] [mozdownload.scraper] Saving as: C:\Users\iris\.iris\cache\firefox-65.0b11-build1.en-US.win64.exe
100% |##########################################################################################################################################################################################################| Time:  0:00:09   4.7 MiB/s
2019-01-25 14:34:06 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/65.0b12-candidates/
2019-01-25 14:34:06 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-01-25 14:34:06 [INFO] [mozdownload.scraper] Selected build: build1
2019-01-25 14:34:06 [INFO] [iris.firefox.firefox_app] Latest available version for beta channel is: 65.0b12
2019-01-25 14:34:06 [INFO] [iris.test_runner] Running tests
2019-01-25 14:34:06 [INFO] [iris.test_runner]
------------------------------------------------------------------------------------------------------------------------
2019-01-25 14:34:06 [INFO] [iris.test_runner] Executing: 1 - [background_update]: This is a test for Firefox background update.
2019-01-25 14:34:11 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Firefox version is correct (65.0b11)
2019-01-25 14:34:11 [INFO] [iris.test_case] Current version: 65.0b11, updating to version: 65.0b12.
2019-01-25 14:35:07 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: Firefox successfully updated from 65.0b11 to 65.0b12.
2019-01-25 14:35:09 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: Firefox version is correct (65.0b12)
2019-01-25 14:35:13 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 4: Background update sanity test passed.
2019-01-25 14:35:14 [INFO] [iris.api.helpers.results] [background_update] - >>> PASSED <<< (Finished in 66.36 second(s))

2019-01-25 14:35:14 [INFO] [iris.test_runner]
------------------------------------------------------------------------------------------------------------------------
2019-01-25 14:35:14 [INFO] [iris.test_runner] Executing: 2 - [manual_update]: This is a test for Firefox manual update.
2019-01-25 14:35:18 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Firefox version is correct (65.0b11).
2019-01-25 14:35:18 [INFO] [iris.test_case] Current version: 65.0b11, updating to version: 65.0b12.
2019-01-25 14:38:40 [WARNING] [iris.test_case] >>> FAILED <<< Step 2: None - [Actual]: None [Expected]: None

-----------------------------------------------------------------------------------
» Traceback (most recent call last):                                              «
»   File "c:\users\iris\iris\iris\test_runner.py", line 69, in run                «
»     current.run()                                                               «
»   File "c:\users\iris\iris\iris\tests\update\manual_update.py", line 46, in run «
»     wait(update_restart_pattern.similar(.7), 200)                               «
»   File "c:\users\iris\iris\iris\api\core\region.py", line 525, in wait          «
»     raise FindError('Unable to find image %s' % image_name.get_filename())      «
» FindError: Unable to find image manual_restart_to_update_button.png             «
-----------------------------------------------------------------------------------

2019-01-25 14:38:52 [WARNING] [iris.api.helpers.general] Firefox is hanging. Executing force quit.
2019-01-25 14:38:53 [INFO] [iris.api.helpers.results] [manual_update] - >>> FAILED <<< (Finished in 205.41 second(s))

2019-01-25 14:38:53 [INFO] [iris.api.helpers.results]
------------------------------------------------------------------------------------------------------------------------
Platform: win, Firefox Version: 65.0, Firefox Build: 20190114172331
Passed: 1, Failed: 1, Skipped: 0 (Blocked: 0), Errors: 0 -- Total: 2                        Total time: 286.43 second(s)

The following tests did not pass:
manual_update


------------------------------------------------------------------------------------------------------------------------
```

**Comment by ashughes1** [comment]
More testing...

**Firefox 63 Beta**
```iris -f 63.0b6 -t manual_update -o```: PASS
```iris -f 63.0b6 -t background_update -o```: PASS
```iris -f 63.0b6 -t background_update,manual_update -o```: FAILED on manual_update step 1 (as in comment 1)
```iris -f 63.0b6 -t manual_update,background_update -o``` FAILED on background_update step 1 (as in comment 1)

**Firefox 65 Beta**
```iris -f 65.0b10 -t manual_update -o```: PASS
```iris -f 65.0b10 -t background_update -o```: PASS
```iris -f 65.0b10 -t background_update,manual_update -o```: FAILED on manual_update step 2 (as in comment 0)
```iris -f 65.0b10 -t manual_update,background_update -o```: FAILED on background_update step 2 (as in comment 0)

**Comment by ashughes1** [comment]
Ah yes, you are right. Thanks for clarifying.
