### ISSUE TITLE
Update tests result in UnicodeDecodeError after restart

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1938]
Running the background update test on Windows 10 for Firefox 65.0b* to 66.0b3 is failing with a UnicodeDecodeError. I wasn't seeing this before 66.0b3 was pushed live so I wonder if this is a regression.

Here is the full output:
```
(iris-R3GGJVZj) C:\Users\iris\iris>iris -t background_update -f 65.0b10 -o
2019-01-28 14:10:37 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/65.0b10-candidates/
2019-01-28 14:10:38 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-01-28 14:10:38 [INFO] [mozdownload.scraper] Selected build: build1
2019-01-28 14:10:38 [INFO] [mozdownload.scraper] Downloading from: https://archive.mozilla.org/pub/firefox/candidates/65.0b10-candidates/build1/win64/en-US/Firefox%20Setup%2065.0b10.exe
2019-01-28 14:10:38 [INFO] [mozdownload.scraper] Saving as: C:\Users\iris\.iris\cache\firefox-65.0b10-build1.en-US.win64.exe
100% |##########################################################################################################################################################################################################| Time:  0:00:04   9.6 MiB/s
2019-01-28 14:10:48 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/66.0b3-candidates/
2019-01-28 14:10:48 [INFO] [mozdownload.scraper] Found 1 build: build1
2019-01-28 14:10:48 [INFO] [mozdownload.scraper] Selected build: build1
2019-01-28 14:10:48 [INFO] [iris.firefox.firefox_app] Latest available version for beta channel is: 66.0b3
2019-01-28 14:10:48 [INFO] [iris.test_runner] Running tests
2019-01-28 14:10:48 [INFO] [iris.test_runner]
------------------------------------------------------------------------------------------------------------------------
2019-01-28 14:10:48 [INFO] [iris.test_runner] Executing: 1 - [background_update]: This is a test for Firefox background update.
2019-01-28 14:10:53 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Firefox version is correct (65.0b10)
2019-01-28 14:10:53 [INFO] [iris.test_case] Current version: 65.0b10, updating to version: 66.0b3.
2019-01-28 14:11:49 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test

----------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                     «
»   File "c:\users\iris\iris\iris\test_runner.py", line 69, in run                                       «
»     current.run()                                                                                      «
»   File "c:\users\iris\iris\iris\tests\update\background_update.py", line 67, in run                    «
»     'Firefox successfully updated from %s to %s.' % (current_version, update_step))                    «
»   File "c:\users\iris\iris\iris\asserts.py", line 49, in assert_contains                               «
»     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) «
»   File "c:\users\iris\iris\iris\test_case.py", line 74, in add_results                                 «
»     '\n' + result.error if result.error else ''))                                                      «
» UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 109: ordinal not in range(128)    «
----------------------------------------------------------------------------------------------------------

2019-01-28 14:11:50 [INFO] [iris.api.helpers.results] [background_update] - >>> ERROR <<< (Finished in 60.87 second(s))

2019-01-28 14:11:50 [INFO] [iris.api.helpers.results]
------------------------------------------------------------------------------------------------------------------------
Platform: win, Firefox Version: 65.0, Firefox Build: 20190110221328
Passed: 0, Failed: 0, Skipped: 0 (Blocked: 0), Errors: 1 -- Total: 1                          Total time: 62.6 second(s)

The following tests did not pass:
background_update


------------------------------------------------------------------------------------------------------------------------
```

**Comment by tracywalker** [comment]
Anthony, I get the same result.  I'm not familiar with these tests.  They were created by the core team.  They may need to take a look.

**Comment by mwobensmith** [comment]
I am getting intermittent pass/fail on the actual test itself, but I do see the error above. That is caused by `api/helpers/results.py`, line 60, function `print_error`. This creates a string for use in logging errors, and it uses Unicode characters for the nice line breaks in the stdout text: `» «`. However, this string is added to an ASCII string later and that causes the above `UnicodeDecodeError`.

I am fixing the underlying text format issues by replacing `«` and `»` with `<<` and `>>`. I dunno what change was made recently that would surface the problem now, but it will fix the immediate error.

**Comment by mwobensmith** [comment]
I haven't found any recent changes that would cause this regression. In theory, the problem was always there. Let's see if that's the end of it.

**Comment by ashughes1** [comment]
Thanks @mwobensmith, this appears to be working now.
