### ISSUE TITLE
Fix user_is_prompted_when_trying_to_close_the_private_window_while_downloading  

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2565]
user_is_prompted_when_trying_to_close_the_private_window_while_downloading  - The user is prompted when trying to close the private window mode  while downloading files.                                 By: rrobotin
--
1 | 4:45:01 AM | Private window successfully loaded. - [Actual]: False [Expected]: True

**Comment by yeyartsev** [comment]
Fails against Windows 7 after third step with traceback:
>> Traceback (most recent call last):
<<
>> File "c:\iris\iris\test_runner.py", line 69, in run
<<
>> current.run()
<<
>> File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_private_window_while_downloading.py", line 56, in run <<
>> download_file(pattern, DownloadFiles.OK)
<<
>> File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file
<<
>> raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')
<<
>> APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by yeyartsev** [comment]
Can not reproduce failure after step 4: 
"Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                                       
>>     current.run()                                                                                                                           
>>   File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_private_window_while_downloading.py", line 56, in run 
>>     download_file(pattern, DownloadFiles.OK)                                                                                                
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file                                                     
>>     raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')                                                  
>> APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by yeyartsev** [comment]
Test fails against win7 after step 4:
"Error encountered in test" for Win 7 with the following stacktrace:

        File "c:\iris\iris\test_runner.py", line 69, in run
        current.run()
        File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_private_window_while_downloading.py", line 56, in run
        download_file(pattern, DownloadFiles.OK)
        File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file
        raise APIHelperError('The 'Save file' option is not present in the page, aborting.')
        APIHelperError: The 'Save file' option is not present in the page, aborting.
