### ISSUE TITLE
Fix full_screen_scroll

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris#2586]
Fix full_screen_scroll

**Comment by yeyartsev** [comment]
>> Traceback (most recent call last):
>> File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/home/user/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/home/user/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/home/user/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/home/user/iris/iris/tests/content_scroll/full_screen_scroll.py", line 46, in run
>> assert_true(self, page_content_displayed, 'Page content displayed.')
>> File "/home/user/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/home/user/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack())))) 

Failed against linux
