### ISSUE TITLE
Fix paste_html 

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris#2699]
paste_html fails on osx with the following stacktrace:
>> Traceback (most recent call last):
>> File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/Users/dev/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/Users/dev/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/Users/dev/iris/iris/tests/drag_and_drop/paste_html.py", line 50, in run
>> assert_true(self, drop_stuff_here_area_pattern, '\'Drop stuff here\' area is displayed on the page')
>> File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by dbakaev** [comment]
Cannot reproduce this failure
