### ISSUE TITLE
Twitter logo not found 

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris#2712]
Pattern twitter_logo.png wasn't found during running insecure_pages_do_not_show test against linux.

>> Traceback (most recent call last):
>> File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/home/user/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/home/user/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/home/user/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/home/user/iris/iris/tests/antivirus/insecure_pages_do_not_show.py", line 27, in run
>> assert_true(self, twitter_page_loaded, 'Twitter webpage is loaded successfully')
>> File "/home/user/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/home/user/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Cannot reproduce
