### ISSUE TITLE
Test case drag_space can fail on WIN10 when more than one Firefox instance/windows are opened.

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2742]
Test case drag_space can fail on WIN10 when more than one Firefox instance/windows are opened.

When running Nightly run, please check if there is another instance of Firefox, or window with similar close/minimize/maximize buttons running on win10, and turn that application/s off. 

2019-04-08 15:48:44 [INFO] [iris.test_runner] Executing: 1 - [drag_space]: This is a test case that checks that the drag space can be activated properly
2019-04-08 15:49:11 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: 'Customize' page successfully loaded.
2019-04-08 15:49:11 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: 'Customize' page is correctly displayed before 'drag space' is enabled
2019-04-08 15:49:12 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: 'Drag space' successfully activated in the 'Customize' page.
2019-04-08 15:49:15 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 4: 'Drag space' successfully activated in a new tab.
2019-04-08 15:49:19 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 5: Window successfully minimized
2019-04-08 15:49:21 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 6: Window in view again
2019-04-08 15:49:21 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 7: The window control 'restore' is visible
2019-04-08 15:49:22 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 8: Window successfully restored
2019-04-08 15:49:23 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 9: Window successfully maximized
2019-04-08 15:49:35 [WARNING] [iris.test_case] >>> FAILED <<< Step 10: None - [Actual]: None [Expected]: None 

-----------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                  <<
>>   File "c:\iris\iris\test_runner.py", line 69, in run                               <<
>>     current.run()                                                                   <<
>>   File "c:\iris\iris\tests\toolbars_window_controls\drag_space.py", line 86, in run <<
>>     raise FindError('Window not closed')                                            <<
>> FindError: Window not closed                                                        <<
-----------------------------------------------------------------------------------------

2019-04-08 15:49:36 [INFO] [iris.api.helpers.results] [drag_space] - >>> FAILED <<< (Finished in 50.7 second(s))

**Comment by tracywalker** [comment]
This is invalid. A machine performing Iris test runs should not have any other applications running, including other instances of Firefox.
