### ISSUE TITLE
Fix insecure_pages_do_not_show test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris#2753]
Can not reproduce failure described at step: ""It's a tracker" site loaded - [Actual]: False [Expected]: True" for OSX with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/Users/dev/iris/iris/tests/antivirus/insecure_pages_do_not_show.py", line 35, in run           
>>     assert_true(self, tracker_site_loaded, '"It\'s a tracker" site loaded')                            
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Cannot reproduce failure against win7 before the first step
