### ISSUE TITLE
Fix bookmark_drag_drop_from_library test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2757]
The test fails at step: "The test page is opened with drag and drop from Library - [Actual]: False [Expected]: True" for Linux with the following stacktrace:
-----------
>> Traceback (most recent call last):                                                                                
>>   File "/home/svuser/.local/share/virtualenvs/iris-zpGrSWP0/bin/iris", line 11, in <module>                       
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                         
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                                    
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                                         
>>   File "/home/svuser/iriscron/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                                 
>>   File "/home/svuser/iriscron/iris/iris/tests/bookmark/bookmark_drag_drop_from_library.py", line 54, in run       
>>     assert_true(self, soap_wiki_opened_from_bookmarks, 'The test page is opened with drag and drop from Library') 
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                                
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by spronoza** [comment]
Fixed already by @alinrus
