### ISSUE TITLE
Fix history_sidebar_sort_by_last_visited

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2768]
Fails intermittently on last Step 10. 
Most likely too small timeout in exist

Stacktrace
>> Traceback (most recent call last):
>> File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/Users/admin/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/Users/admin/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/Users/admin/iris/iris/tests/history/history_sidebar_sort_by_last_visited.py", line 53, in run
>> assert_true(self, expected_4, 'Focus page loaded successfully.')
>> File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
The pattern not found and in next run was found. Intermittent failre.

![image](https://user-images.githubusercontent.com/45387203/63758021-a92ffa00-c8aa-11e9-84be-729d32b8ee78.png)

![image](https://user-images.githubusercontent.com/45387203/63758030-acc38100-c8aa-11e9-9ed3-7199f595c60e.png)
