### ISSUE TITLE
Fix delete_bookmark_from_library test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2779]
Can not reproduce failure described at step: "The Wikipedia bookmark is successfully added - [Actual]: False [Expected]: True" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/bookmark/delete_bookmark_from_library.py", line 51, in run          
>>     assert_true(self, wiki_bookmark_added, 'The Wikipedia bookmark is successfully added')             
>>   File "/home/user/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by spronoza** [comment]
The failure is still reproducible for Linux

**Comment by spronoza** [comment]
Reproduced and fixed
