### ISSUE TITLE
Fix disable_search_suggestions test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2802]
Can not reproduce failure described at step: "Checkbox displayed in front of the 'Show search suggestions in address bar results' text is unchecked. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:
--------
>> Traceback (most recent call last):                                                                             
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>                      
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                      
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                                 
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                                      
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                              
>>   File "/Users/dev/iris/iris/tests/awesomebar/disable_search_suggestions.py", line 73, in run                  
>>     assert_true(self, expected, 'Checkbox displayed in front of the \'Show search suggestions in address bar ' 
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                             
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Lowering similarity of pattern from 0.9 to 0.8 fixes issue

2019-04-12 14:43:13,401 [INFO] [iris.test_runner] Executing: 1 - [disable_search_suggestions]: This test case disables search suggestions in awesomebar.
2019-04-12 14:43:27,550 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Page successfully loaded, firefox logo found.
2019-04-12 14:43:36,241 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: With default value for the 'Show search suggestions in address bar results' option the 'Google' search engine is found after 10 scrolls through the suggestions list.
2019-04-12 14:43:36,594 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: The 'Search settings' button is displayed in the awesomebar.
2019-04-12 14:43:39,217 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 4: The 'about:preferences#search' page successfully loaded.
2019-04-12 14:43:39,583 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 5: Checkbox displayed in front of the 'Show search suggestions in address bar results' text is checked by default.
2019-04-12 14:43:52,224 [WARNING] [iris.test_case] >>> FAILED <<< Step 6: Checkbox displayed in front of the 'Show search suggestions in address bar results' text is unchecked. - [Actual]: False [Expected]: True 

--------------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                             <<
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>                      <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                      <<
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                                    <<
>>     run_iris()                                                                                                 <<
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                               <<
>>     run(master_test_list, tests, browser)                                                                      <<
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                                  <<
>>     current.run()                                                                                              <<
>>   File "/Users/dev/iris/iris/tests/awesomebar/disable_search_suggestions.py", line 73, in run                  <<
>>     assert_true(self, expected, 'Checkbox displayed in front of the \'Show search suggestions in address bar ' <<
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                              <<
>>     assert_equal(test_case, actual, True, message)                                                             <<
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                             <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))         <<
--------------------------------------------------------------------------------------------------------------------

2019-04-12 14:43:56,294 [INFO] [iris.api.helpers.results] [disable_search_suggestions] - >>> FAILED <<< (Finished in 38.82 second(s))

2019-04-12 14:43:56,299 [INFO] [iris.api.helpers.results] 
------------------------------------------------------------------------------------------------------------------------
Platform: osx, Firefox Version: 67.0, Firefox Build: 20190411084603
Passed: 0, Failed: 1, Skipped: 0 (Blocked: 0), Errors: 0 -- Total: 1                          Total time: 42.9 second(s)

The following tests did not pass:
disable_search_suggestions
