### ISSUE TITLE
Fix one_off_search_engines_can_be_disabled_enabled test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2804]
The test fails at step: "Element found at position 0 in the list found. - [Actual]: False [Expected]: True" for Linux with the following stacktrace:
--------
>> Traceback (most recent call last):                                                                             
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>                      
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                      
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                                 
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                                      
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                              
>>   File "/home/user/iris/iris/tests/search/one_off_search_engines_can_be_disabled_enabled.py", line 124, in run 
>>     assert_true(self, expected, 'Element found at position ' + i.__str__() + ' in the list found.')            
>>   File "/home/user/iris/iris/asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                             
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This is failing in daily runs with ```The 'DuckDuckGo' one-off button found.```. I also confirmed this test failure locally.
