### ISSUE TITLE
[AttributeError] Failure to exectute sample test cases

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/iris#476]
Running `iris sample -i DEBUG` on macOS Mojave (ver. 10.14.5) fails with the following debug  and traceback output. Let me know what additional information I can provide that would be useful. Cheers and ty for the help.

Python 3.7.3

```
iris git:(master) ✗ iris sample -i DEBUG
2019-07-02 11:42:11 [DEBUG] Old Iris 1 install exists: False
2019-07-02 11:42:11 [DEBUG] Old Iris 2 install exists: False
2019-07-02 11:42:15 [DEBUG] sample target module found!
2019-07-02 11:42:15 [DEBUG] Path /Users/mbrandt/workspace/iris/tests/sample found. Checking content ...
2019-07-02 11:42:15 [DEBUG] List of all tests found: [/Users/mbrandt/workspace/iris/tests/sample/section1/section1_1/test_1.py, /Users/mbrandt/workspace/iris/tests/sample/section2/test_2.py]
2019-07-02 11:42:15 [INFO] Desired target: sample
2019-07-02 11:42:16 [INFO] Found target named Sample
2019-07-02 11:42:16 [DEBUG] Registering cleanup handler
2019-07-02 11:42:16 [DEBUG] Platform does not require switching terminal encoding
2019-07-02 11:42:16 [DEBUG] Old Iris 1 install exists: False
2019-07-02 11:42:16 [DEBUG] Old Iris 2 install exists: False
2019-07-02 11:42:16 [INFO]
------------------------------------------------------------Test session sample started------------------------------------------------------------
2019-07-02 11:42:16 [INFO]
Iris settings:
target: sample, rerun: False, highlight: False, clear: False, email: False, level: 10, control: False, locale: en-US, mouse: 0.5, no_check: False, override: False, port: 2000, test: , workdir: /Users/mbrandt/.iris, exclude: , resize: False, virtual_keyboard: False
2019-07-02 11:42:16 [INFO]
Sample settings:
sample_first_argument: sample first argument, sample_second_argument: sample second argument, sample_third_argument: sample third argument
2019-07-02 11:42:16 [DEBUG] Updating run file: /Users/mbrandt/.iris/data/runs.json
=============================================================== test session starts ===============================================================
platform darwin -- Python 3.7.3, pytest-5.0.0, py-1.8.0, pluggy-0.12.0 -- /Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/bin/python3
cachedir: .pytest_cache
rootdir: /Users/mbrandt/workspace/iris/tests/sample, inifile: pytest.ini
plugins: mozlog-4.0
collected 2 items

tests/sample/section1/section1_1/test_1.py::Test::run 2019-07-02 11:42:16 [DEBUG] Module test_1.py requests image test.png
2019-07-02 11:42:16 [DEBUG] Found /Users/mbrandt/workspace/iris/tests/sample/section1/section1_1/images/osx/test.png
2019-07-02 11:42:16 [DEBUG] Searching image with similarity 0.8
2019-07-02 11:42:16 [DEBUG] Min location -0.1611412763595581 and max location 0.16255517303943634
2019-07-02 11:42:16 [DEBUG] Test failed with error
FAILED
tests/sample/section2/test_2.py::Test::run PASSED2019-07-02 11:42:17 [DEBUG] Updating run file: /Users/mbrandt/.iris/data/runs.json
2019-07-02 11:42:17 [INFO]
--------------------------------------------------------------------Test Report--------------------------------------------------------------------
Application: Sample, Platform: osx
Passed: 1, Failed: 0, Skipped: 0, Errors 1  -- Total: 2                                                                    Total time: 00:00:00.245

The following tests did not pass:
test_1.py


---------------------------------------------------------------------------------------------------------------------------------------------------

2019-07-02 11:42:17 [DEBUG] Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/mbrandt/workspace/iris, universal_newlines=False, shell=None)
2019-07-02 11:42:17 [DEBUG] Updating run.json with completed run data.
Traceback (most recent call last):
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/mbrandt/workspace/iris/src/__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/_pytest/terminal.py", line 649, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mbrandt/.virtualenvs/iris-OgMC9Iu-/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mbrandt/workspace/iris/src/base/target.py", line 94, in pytest_sessionfinish
    create_run_log(self)
  File "/Users/mbrandt/workspace/iris/src/core/util/json_utils.py", line 142, in create_run_log
    tests = {'all_tests': convert_test_list(app.completed_tests),
  File "/Users/mbrandt/workspace/iris/src/core/util/json_utils.py", line 188, in convert_test_list
    'error': test.error.lstrip(), 'message': test.message.lstrip(), 'call_stack': test.traceback + '\n\n ',
AttributeError: 'NoneType' object has no attribute 'lstrip'

```

**Comment by KWierso** [comment]
This seems to be happening if an exception is raised, but it doesn't have the required information for `test_assert`.

For my case, I'm trying to fix https://github.com/mozilla/iris_firefox/issues/3217 and am running just that one test and hit this AttributeError. A lot of pieces of test metadata are NoneType.

I've tried papering over some of these things by changing [this section](https://github.com/mozilla/iris_firefox/blob/master/src/core/util/json_utils.py#L187-L190) like this:
```
test_assert = {
   'error': test.error.lstrip() if test.error is not None else "",
   'message': test.message.lstrip() if test.message is not None else "",
   'call_stack': test.traceback + '\n\n ',
   'code': get_failing_code(test.node_name, int(test.line) if test.line is not None else 0)
}
```

But that has its own failure: 
```
  File "/Users/wkocher/mozilla/iris_firefox/src/core/util/json_utils.py", line 232, in get_failing_code
    f = open(file, 'rb').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '<ExceptionInfo APIHelperError tblen=20>'
```

A Pretty Printed breakdown of `test`'s various properties when I hit this:
```
{'actual': None,
 'error': None,
 'expected': None,
 'file_name': '/Users/wkocher/mozilla/iris_firefox/tests/firefox/history/history_sidebar_copy_site_to_bookmarks_toolbar.py',
 'item': <Function run>,
 'line': None,
 'message': None,
 'node_name': '<ExceptionInfo APIHelperError tblen=20>',
 'outcome': 'ERROR',
 'test_duration': 24.93958616256714,
 'traceback': 'Traceback (most recent call last):\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/_pytest/runner.py':220 "
              'in from_call\n'
              '  result = func()\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/_pytest/runner.py':192 "
              'in <lambda>\n'
              '  return CallInfo.from_call(\n'
              '        lambda: ihook(item=item, **kwds), when=when, '
              'reraise=reraise\n'
              '    )\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/hooks.py':289 "
              'in __call__\n'
              '  return self._hookexec(self, self.get_hookimpls(), kwargs)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/manager.py':87 "
              'in _hookexec\n'
              '  return self._inner_hookexec(hook, methods, kwargs)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/manager.py':81 "
              'in <lambda>\n'
              '  self._inner_hookexec = lambda hook, methods, kwargs: '
              'hook.multicall(\n'
              '            methods,\n'
              '            kwargs,\n'
              '            firstresult=hook.spec.opts.get("firstresult") if '
              'hook.spec else False,\n'
              '        )\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':208 "
              'in _multicall\n'
              '  return outcome.get_result()\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':80 "
              'in get_result\n'
              '  raise ex[1].with_traceback(ex[2])\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':187 "
              'in _multicall\n'
              '  res = hook_impl.function(*args)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/_pytest/runner.py':117 "
              'in pytest_runtest_call\n'
              '  item.runtest()\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/_pytest/python.py':1451 "
              'in runtest\n'
              '  self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/hooks.py':289 "
              'in __call__\n'
              '  return self._hookexec(self, self.get_hookimpls(), kwargs)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/manager.py':87 "
              'in _hookexec\n'
              '  return self._inner_hookexec(hook, methods, kwargs)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/manager.py':81 "
              'in <lambda>\n'
              '  self._inner_hookexec = lambda hook, methods, kwargs: '
              'hook.multicall(\n'
              '            methods,\n'
              '            kwargs,\n'
              '            firstresult=hook.spec.opts.get("firstresult") if '
              'hook.spec else False,\n'
              '        )\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':208 "
              'in _multicall\n'
              '  return outcome.get_result()\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':80 "
              'in get_result\n'
              '  raise ex[1].with_traceback(ex[2])\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/pluggy/callers.py':187 "
              'in _multicall\n'
              '  res = hook_impl.function(*args)\n'
              '\n'
              '    File '
              "'/Users/wkocher/.local/share/virtualenvs/iris_firefox-lpZr6UvV/lib/python3.7/site-packages/_pytest/python.py':165 "
              'in pytest_pyfunc_call\n'
              '  testfunction(**testargs)\n'
              '\n'
              '    File '
              "'/Users/wkocher/mozilla/iris_firefox/tests/firefox/history/history_sidebar_copy_site_to_bookmarks_toolbar.py':35 "
              'in run\n'
              '  access_bookmarking_tools(view_bookmarks_toolbar)\n'
              '\n'
              '    File '
              "'/Users/wkocher/mozilla/iris_firefox/targets/firefox/firefox_ui/helpers/general.py':51 "
              'in access_bookmarking_tools\n'
              '  open_library_menu(LibraryMenu.BOOKMARKS_OPTION)\n'
              '\n'
              '    File '
              "'/Users/wkocher/mozilla/iris_firefox/targets/firefox/firefox_ui/helpers/general.py':755 "
              'in open_library_menu\n'
              '  raise APIHelperError(\n'
              "            'Can\\'t find the library menu in the page, "
              "aborting test.')\n"
              '\n'
              '  None: None'}
```

**Comment by KWierso** [comment]
> ```
>  'node_name': '<ExceptionInfo APIHelperError tblen=20>',
> ```

So it seems like somewhere in the code, we're raising an APIHelperError, and that's getting assigned as the `node_name` for the assert, rather than the appropriate filename?

**Comment by dbakaev** [comment]
When we deploy iris to a new environment run.json is not getting created if any tests fail.
Also, when this happens all failed tests in report will be shown as 'Errors', not 'Failed'
```
2019-07-25 12:15:42 [DEBUG] Updating run.json with completed run data.
Traceback (most recent call last):
  File "C:\Users\sharapov\.virtualenvs\iris_firefox-UVWxEEh6\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "d:\code\iris_firefox\src\__main__.py", line 81, in main
    pytest.main(pytest_args, plugins=[target_plugin])
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\_pytest\config\__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\_pytest\main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\_pytest\main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\_pytest\terminal.py", line 649, in pytest_sessionfinish
    outcome.get_result()
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\sharapov\.virtualenvs\iris_firefox-uvwxeeh6\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "d:\code\iris_firefox\targets\firefox\main.py", line 122, in pytest_sessionfinish
    BaseTarget.pytest_sessionfinish(self, session)
  File "d:\code\iris_firefox\src\base\target.py", line 94, in pytest_sessionfinish
    create_run_log(self)
  File "d:\code\iris_firefox\src\core\util\json_utils.py", line 148, in create_run_log
    tests = {'all_tests': convert_test_list(app.completed_tests),
  File "d:\code\iris_firefox\src\core\util\json_utils.py", line 194, in convert_test_list
    'error': test.error.lstrip(), 'message': test.message.lstrip(), 'call_stack': test.traceback + '\n\n ',
AttributeError: 'NoneType' object has no attribute 'lstrip'

```
