### ISSUE TITLE
Linux: Problem with pyperclip paste method

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#70]
On a clean Ubuntu 16.04.4 image, with a new clone and install of Iris, I see this error when I run a test. Let's find out what causes it and try to fix, or temporarily change the parts of Iris that rely on it.

```
2018-04-25 00:44:56 [INFO] [iris.test_runner] Executing: 1 - This is a test of a bunch of tabs 
Traceback (most recent call last):
  File "/home/mozilla/iris/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/home/mozilla/iris/iris/__main__.py", line 37, in main
    Iris()
  File "/home/mozilla/iris/iris/__main__.py", line 50, in __init__
    test_runner.run(self)
  File "/home/mozilla/iris/iris/test_runner.py", line 54, in run
    current.run()
  File "/home/mozilla/iris/iris/tests/experiments/tabs.py", line 29, in run
    navigate("https://www.google.com/?hl=EN")
  File "/home/mozilla/iris/iris/api/helpers/general.py", line 84, in navigate
    paste(url)
  File "/home/mozilla/iris/iris/api/core.py", line 1181, in paste
    pyperclip.copy(text)
  File "/home/mozilla/iris/local/lib/python2.7/site-packages/pyperclip/__init__.py", line 574, in lazy_load_stub_copy
    return copy(text)
  File "/home/mozilla/iris/local/lib/python2.7/site-packages/pyperclip/__init__.py", line 284, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 

```

**Comment by mwobensmith** [comment]
Found a solution - add `xsel` to linux bootstrap script seems to fix this. Will check in and test.

**Comment by mwobensmith** [comment]
Fixed and landed with prototype work.
