### ISSUE TITLE
Use pipenv with Pipfile for installation and execution

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#858]
This issue will be used to track @davehunt 's work that will allow us to use pipenv/Pipfile.

**Comment by mwobensmith** [comment]
When I run `iris -t empty`, I get the following:

```

2018-07-23 16:06:26 [INFO] [iris.test_runner] Running tests
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 418, in <module>
    main()
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 46, in main
    Iris()
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 68, in __init__
    run(self)
  File "iris/test_runner.py", line 30, in run
    current_module = importlib.import_module(module)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named empty
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
```

**Comment by mwobensmith** [comment]
Also, we need to add `pip install pipenv` to both bootstrap scripts as well as Windows [setup instructions](https://github.com/mozilla/iris/wiki/Setup).

**Comment by davehunt** [comment]
I've fixed the `ImportError` by installing Iris in the environment so the test modules are available for import. I've also added installation of Pipenv to the two bootstrap files. See https://github.com/mozilla/iris/pull/880. I wasn't aware of the wiki for documentation (I'd suggest adding a link from the README). I'd be happy to update this once this issue has been resolved.

I'd also suggest any documentation pertaining to the code be kept alongside the code. This means changes can be made in both places at the same time. For a project this size, perhaps consider using [Sphinx](http://www.sphinx-doc.org/en/stable/) to build and publish to https://readthedocs.org/. This is another area I'd be happy to assist with.

**Comment by mwobensmith** [comment]
Thanks @davehunt - much appreciated.

I am running into a different error now:
```
Traceback (most recent call last):
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/bin/iris", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/mwobensmith/.local/share/virtualenvs/iris-qxLEFYfH/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'monotonic; python_version == "2.6" or python_version == "2.7" or python_version == "3.0" or python_version == "3.1" or python_version == "3.2"' distribution was not found and is required by humanfriendly
```
Not sure what to do here.

Other items:
* We added a dependency to Iris for `GitPython`, so we will need to add it here too.
* Moving the calls for `pip install pyobjc` and `pip install pyobjc-core` out of the Mac bootstrap script and into the `setup.py` script exposes existing issue #72 (and on Linux, #71 for `xlib`). If we drop support for the `setup.py` file, then this is OK, but otherwise we need a solution that works for all of the install methods. 
* Our documentation is indeed becoming dated and we need to update it at some point. We will for sure by 1.0 release. Any help you can provide is appreciated, and I will read up on Sphinx as you suggest. 👍🏼

**Comment by davehunt** [comment]
> Not sure what to do here.

It looks like pip was unable to find and install monotonic. Is it possible this was a transient issue? Are you still able to reproduce this?

> We added a dependency to Iris for GitPython, so we will need to add it here too.

Yes, any new dependencies will need to be added to the `Pipfile` and `Pipfile.lock`. This can be done by running `pipenv install GitPython` if you want the latest available version. If you want this to depend on the platform, or by pinned to a specific version, then further edits will need to be made.

> Moving the calls for pip install pyobjc and pip install pyobjc-core out of the Mac bootstrap script and into the setup.py script exposes existing issue #72 (and on Linux, #71 for xlib). If we drop support for the setup.py file, then this is OK, but otherwise we need a solution that works for all of the install methods.

The problem with these being in the bootstrap script is that they will be installed in the current context. If a virtual environment is not active then that means these will be installed in the user's globabl site packages. Note that you shouldn't remove `setup.py` as it's being used by Pipenv to create the environment, but it shouldn't be used to install Iris as the versions of the dependencies will not be known to work, like the ones defined in `Pipfile.lock`.

**Comment by davehunt** [comment]
On reflection, as you're running on multiple platforms it probably doesn't make sense to have a `Pipfile.lock`. Having a `Pipfile` and using `pipenv` could still be valuable as a convenient way to manage your virtual environment, but you'd likely be generating the lock file often, which is an expensive operation. If you were running these on a single platform, the `Pipfile.lock` would save time and keep your environment consistent. I guess what I'm saying is that maybe you don't want to use pipenv, and that's fine. 😄

**Comment by AndreiH** [comment]
After our discussion on Slack, I did some more investigation and work into this.
It seems that `Pipfile.lock` does not update any more based on the platform we run `pipenv install`. It remains the same, and `pipenv` works great on all platforms.
In my opinion we can give it a try, `Pipenv` being very helpful.

**Comment by mwobensmith** [comment]
Thanks @davehunt and @AndreiH , sounds like this gives us another option, so why not? 😄

**Comment by AndreiH** [comment]
There was a library that was installing only on Mac platform, which always changed `Pipfile.lock`, when running `pipenv install`. That library is `pyobjc-framework-cocoa` which I added to `Pipfile`. and now `Pipfile.lock` remains the same.

This can be reviewed and tested on branch `issue_858`
Steps to setup and run `Iris` with `Pipenv`:
1. Switch on testing branch
2. Run `sh bootstrap/bootstrap.sh`, this will install Pipenv also, based on the Platform.
3. Install all requirements with `pipenv install`
4. Switch on created virtualenv with `pipenv shell`
5. Run Iris
