### ISSUE TITLE
Intermittent error with pyautogui.screenshot

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#933]
I saw this recently, on Mac:
```

2018-08-03 12:44:39 [INFO] [iris.test_runner] Executing: 39 - [zoom_in_hamburger_menu]: This is a test case that checks the zoom in functionality from the hamburger menu.
Traceback (most recent call last):
  File "/Users/username/PycharmProjects/iris/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/username/PycharmProjects/iris/iris/__main__.py", line 47, in main
    Iris()
  File "/Users/username/PycharmProjects/iris/iris/__main__.py", line 70, in __init__
    run(self)
  File "/Users/username/PycharmProjects/iris/iris/test_runner.py", line 80, in run
    current.run()
  File "/Users/username/PycharmProjects/iris/iris/tests/./zoom_indicator/zoom_in_hamburger_menu.py", line 46, in run
    new_region = create_region_for_hamburger_menu()
  File "/Users/username/PycharmProjects/iris/iris/api/helpers/general.py", line 427, in create_region_for_hamburger_menu
    region = create_region_from_patterns(None, hamburger_menu_pattern, help_menu, None, padding_right=20)
  File "/Users/username/PycharmProjects/iris/iris/api/core/region.py", line 224, in create_region_from_patterns
    current_pattern = find(pattern)
  File "/Users/username/PycharmProjects/iris/iris/api/core/region.py", line 531, in find
    image_found = image_search(pattern, region)
  File "/Users/username/PycharmProjects/iris/iris/api/core/util/image_search.py", line 182, in image_search
    stack_image = get_region(region=region)
  File "/Users/username/PycharmProjects/iris/iris/api/core/util/core_helper.py", line 171, in get_region
    grabbed_area = pyautogui.screenshot(region=(0, 0, SCREENSHOT_WIDTH, SCREENSHOT_HEIGHT))
  File "/Users/username/PycharmProjects/iris/lib/python2.7/site-packages/pyscreeze/__init__.py", line 342, in _screenshot_osx
    os.unlink(tmpFilename)
OSError: [Errno 2] No such file or directory: '.screenshot2018-0803_12-45-02-531154.png'
```

It seems that `pyautogui.screenshot` saves a temp file that is deleted (?) later. I have noticed these in the project root, filenames starting with `.` . I think we should perhaps wrap calls to this API in some of our own code, with `try`/`except` to catch any potential exceptions, which we don't care about anyway.

**Comment by mwobensmith** [comment]
Possible solution - force change to current directory, if this is a permission issue.

```
import os
foo = some_directory_that_we_can_write_to
os.chdir(foo)
```

**Comment by mwobensmith** [comment]
Another solution - use a temporary file name and path when calling `pyautogui.screenshot,` as this could be a Mac-only issue where the default path could be causing problems. See [this](https://stackoverflow.com/questions/27292528/run-os-x-screencapture-from-emacs-call-process) for more info.
