### ISSUE TITLE
AttributeError: 'Iris' object has no attribute 'process_list' when trying to run Iris with 'Num Lock' ON

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#974]
Running an Iris test with the 'Num Lock' button ON throws, instead of a suggestive message, the following:

iris -t tabs
No handlers could be found for logger "iris.__main__"
Traceback (most recent call last):
  File "C:\iris\venv\Scripts\iris-script.py", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "c:\iris\iris\__main__.py", line 49, in main
    Iris()
  File "c:\iris\iris\__main__.py", line 57, in __init__
    self.verify_config()
  File "c:\iris\iris\__main__.py", line 64, in verify_config
    self.check_keyboard_state()
  File "c:\iris\iris\__main__.py", line 327, in check_keyboard_state
    self.finish(code=1)
  File "c:\iris\iris\__main__.py", line 304, in finish
    logger.debug('There are %s queued process(es) to terminate.' % len(self.process_list))
AttributeError: 'Iris' object has no attribute 'process_list'

**Comment by tracywalker** [comment]
This was working correctly as of early last week.  However, I can reproduce this issue, at least on Linux where I have a NumLock key.

note: I've seen this "AttributeError: 'Iris' object has no attribute 'process_list'" as the last line of several errors, in various test cases, when I ran the entire suite on Friday.
